export const language = {
  emptyText: 'No series have been found. If you\'re searching for a specific series, try using a different name or provider.',
  errorProviderBody: 'An error occurred. The provider could not be opened. Try again momentarily. If this error continues, open a support ticket.',
  errorProviderButtons: ['Cancel', 'Retry'],
  errorSeriesBody: 'An error occurred. The series could not be opened. Try again momentarily. If this error continues, open a support ticket.',
  errorSeriesButtons: ['Cancel', 'Retry'],
  errorStreamBody: 'An error occurred. The stream could not be opened. If this is a premium stream, check your login and subscription.',
  errorStreamButtons: ['Cancel', 'Retry'],
  errorSessionBody: 'An error occurred. The stream could not be played. Try again momentarily. If this error continues, open a support ticket.',
  errorSessionButtons: ['Cancel', 'Retry'],
  errorText: 'An error occurred.',
  seriesPremium: 'premium',
  seriesSeason: 'There are no episodes available for this season.',
  seriesSynopsis: 'There is no synopsis available for this series.',
};
